### ISSUE TITLE
Don't work with php 7.3.5

### ISSUE THREAD

**Issue by Minzord** [featherbb/featherbb#146]
Hello, featherbb don't work with php 7.3.5

`Fatal error: Uncaught Error: Call to undefined function __() in /usr/share/nginx/mountain-linux-forum/fr/featherbb/routes.php:250 Stack trace: #0 [internal function]: {closure}(Object(Slim\Http\Request), Object(Slim\Http\Response), Object(Exception)) #1 /usr/share/nginx/mountain-linux-forum/fr/vendor/slim/slim/Slim/App.php(703): call_user_func_array(Object(Closure), Array) #2 /usr/share/nginx/mountain-linux-forum/fr/vendor/slim/slim/Slim/App.php(407): Slim\App->handleException(Object(Exception), Object(Slim\Http\Request), Object(Slim\Http\Response)) #3 /usr/share/nginx/mountain-linux-forum/fr/vendor/slim/slim/Slim/App.php(313): Slim\App->process(Object(Slim\Http\Request), Object(Slim\Http\Response)) #4 [internal function]: Slim\App->run() #5 /usr/share/nginx/mountain-linux-forum/fr/vendor/statical/statical/src/BaseProxy.php(60): call_user_func_array(Array, Array) #6 /usr/share/nginx/mountain-linux-forum/fr/index.php(56): Statical\BaseProxy::__callStatic('run', Array) #7 {main} thrown in /usr/share/nginx/mountain-linux-forum/fr/featherbb/routes.php on line 250`

**Comment by adaur** [comment]
Hi,

That's odd. I run 7.3.5 locally and I have no problem. The function __ is used to translate strings, are you sure your composer dependencies are properly installed?

**Comment by adaur** [comment]
Actually it may fail because of something else and this error is coming from the error displaying. Can you try to install your forum using the development branch and see if it persists?

**Comment by Minzord** [comment]
Yes it work. I forgot to put the chmod.
https://forum.mountain-linux.eu.org/fr/

**Comment by Minzord** [comment]
But have you got a nginx config because my config word work with url http://forum.mountain-linux.eu.org/fr/install

**Comment by Minzord** [comment]
If you prefere i'm online in Gitter.

**Comment by Minzord** [comment]
Don't work http://forum.mountain-linux.eu.org/fr/install
return File not found. 

server {

    listen 80;
    server_name www.forum.mountain-linux.eu.org forum.mountain-linux.eu.org;
    root /usr/share/nginx/mountain-linux-forum;
    index index.php index.html;

location / {
        try_files $uri $uri/ /index.php$is_args$args;
}

location ~ \.css {
    add_header  Content-Type    text/css;
}
location ~ \.js {
    add_header  Content-Type    application/x-javascript;
}

location ~ \.php$ {
        include /etc/nginx/fastcgi_params;
        fastcgi_pass  127.0.0.1:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
}


}

**Comment by adaur** [comment]
If you want your forum to be installed in the /fr folder, it should probably be

```
location /fr/ {
root /usr/share/nginx/mountain-linux-forum/fr;
try_files $uri $uri/ /index.php$is_args$args;
}
```

but maybe it's best to have it at the root of http://forum.mountain-linux.eu.org ?

Also make sure your files are in /usr/share/nginx/mountain-linux-forum if the forum is at the root, /usr/share/nginx/mountain-linux-forum/fr if it's in the fr folder

**Comment by Minzord** [comment]
I fix the conf but it's don't work: 
http://forum.mountain-linux.eu.org/fr/
`File not found.`

**Comment by Minzord** [comment]
I fix the conf of nginx but I have to add index.php to the url for it work.
And http://forum.mountain-linux.eu.org/fr/index.php/install 
`File not found.`

**Comment by adaur** [comment]
In case it helps, here is the configuration of forums.featherbb.org minus the SSL
```
server
{
    listen 443 ssl http2;
    listen [::]:443 ssl http2;

    server_name     forums.featherbb.org;
    access_log /var/log/nginx/forums.featherbb.org.access;
    error_log /var/log/nginx/forums.featherbb.org.error error;

    location /
    {
            root    /var/www/featherbb;
            try_files $uri $uri/ /index.php?$query_string;

            index   index.php index.html index.htm;
            rewrite ^/latest_version$ /latest_version.html last;
    }

    location ~ /.+\.(jpg|jpeg|gif|css|png|js|ico|xml|ttf|eot|svg|woff)$
    {
            root    /var/www/featherbb;
    }

    location ~ /\.ht
    {
            deny  all;
    }

    location ~ /\.env
    {
            deny  all;
    }

    location ~ \.php$
    {
            fastcgi_pass    127.0.0.1:9000;
            fastcgi_index   index.php;
            include fastcgi_params;
            fastcgi_param  SCRIPT_FILENAME  /var/www/featherbb$fastcgi_script_name;
            client_max_body_size 50M;
            fastcgi_connect_timeout 60;
            fastcgi_send_timeout 180;
            fastcgi_read_timeout 180;
            fastcgi_buffer_size 128k;
            fastcgi_buffers 256 16k;
            fastcgi_busy_buffers_size 256k;
            fastcgi_temp_file_write_size 256k;
            proxy_connect_timeout 300;
    }
}
```
The code lives in ` /var/www/featherbb`

I think your problem comes from the extra /fr folder

Something is wrong with your configuration but it's hard to tell you what without the virtual host and the folders... I would try to put featherbb at the root of the virtual host forum.mountain-linux.eu.org and minmic the configuration I posted above

**Comment by Minzord** [comment]
I click on `Start Install` and i'm redirect vers install page.

**Comment by adaur** [comment]
I'm not sure what's going on here... make sure your parameters are correct and that you have write permission. Everything is working for me locally I tried the installer recently. Maybe try to install it locally to see if it works.

**Comment by adaur** [comment]
Hm I can think of something else. Make sure that you run the install script at http://forum.mountain-linux.eu.org/install
